wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/search", views.search, name="search"),
    path("wiki/new", views.newPage, name = "newPage"),
    path("wiki/random", views.randomPage, name = "randomPage"),
    path("wiki/<str:entry_name>", views.entry, name="entry"),
    path("wiki/<str:entry>/edit", views.editPage, name = "editPage"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

import markdown2
import re
from . import util
from random import choice

class EntryForm(forms.Form):
    title = forms.CharField(label = "Title")
    content = forms.CharField(label = "Content", widget = forms.Textarea)

def search(request):

    entries = util.list_entries()

    query = request.GET['q']

    search_entries = []
    for entry in entries:
        if query.lower() == entry.lower():
            return HttpResponseRedirect(f"/wiki/{entry}")
        elif re.search(query.lower(), entry.lower()):
            search_entries.append(entry)
        else:
            continue

    return render(request, "encyclopedia/search.html", {
            "entries": search_entries
    })

def newPage(request):

    # Check if method is POST
    if request.method == "POST":

        exists = False
        error = ''
        # Take in the data the user submitted and save it as form
        form = EntryForm(request.POST)

        if form.is_valid():

            # Isolate the task from the 'cleaned' version of form data
            title = form.cleaned_data["title"]
            content = "# " + title + "\n" + form.cleaned_data["content"]

            entries = [entry.lower() for entry in util.list_entries()]

            if title.lower() not in entries:
                # Add the new entry
                util.save_entry(title, content)

            else:
                exists = True
                error = f"{title} already exists"
                return render(request, "encyclopedia/new.html", {
                    "form": EntryForm(), "error": error, "exists":exists
                })

            # Redirect user to entry page
            return HttpResponseRedirect(f"/wiki/{title}")


    # If the form is invalid, re-render the page with existing information.
    return render(request, "encyclopedia/new.html", {
        "form": EntryForm()
    })

def randomPage(request):
     page = choice(util.list_entries())
     return HttpResponseRedirect(f"{page}")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entry(request, entry_name):

    fullEntry = util.get_entry(entry_name)


    if not fullEntry:
        #Go to Page not found
        return render(request, "encyclopedia/notFound.html")
    else:
        fullEntry = markdown2.markdown(fullEntry)

        title = re.search(entry_name, fullEntry, re.IGNORECASE).group()

        return render(request, "encyclopedia/entry.html", {
            "title": title, "entry": fullEntry
        })

def editPage(request, entry):

    #initialise dictionary with form data
    content = util.get_entry(entry)
    content = re.sub(f"# {entry}", '', content)
    context = {"title": entry, "content": content}

    #instantiate form with dictionary as initial argument

    form = EntryForm(request.POST or None, initial = context)

    if form.is_valid():

        # Isolate the task from the 'cleaned' version of form data
        title = form.cleaned_data["title"]
        content = "# " + title + "\n" + form.cleaned_data["content"]
        util.save_entry(entry, content)

        # Redirect user to entry page
        return HttpResponseRedirect(f"/wiki/{title}")

    return render(request, "encyclopedia/edit.html", {
        "form": form, "path":entry, "content": content
    })

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit
{% endblock %}

{% block body %}

  <form action="{% url 'encyclopedia:editPage' path %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
  </form>


{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
  {{entry|safe}}
  <form action="{% url 'encyclopedia:editPage' title %}">
      <button type="submit">Edit</button>
  </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
              <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randomPage' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  Create New Page
{% endblock %}

{% block body %}
  <h1>Create a new page</h1>

  <h3>Markdown Syntax:</h3>
  <ul>
    <li>Heading: #</li>
    <li>Smaller heading: ##</li>
    <li>Bold: **...**</li>
    <li>Italic: *...*</li>
    <li>Strikethrough: ~~  ~~ </li>
    <li>Subscript: <sub></sub></li>
    <li>Superscript: <sup></sup></li>
    <li>Quote: > </li>
  </ul>

    {% if exists %}
      <p class = "bg-light text-danger">{{error}}</p>
    {% endif %}

    <form action="{% url 'encyclopedia:newPage' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/notFound.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
  Not Found
{% endblock %}

{% block body %}
  <h1>Entry doesn't exist</h1>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    {% if entries|length > 0 %}
    <ul>
      Partial Matches:
        {% for entry in entries %}
            <li>
              <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
    {% else %}
    No Matches
    {% endif %}

{% endblock %}